### ISSUE TITLE
docker image of RapidSCADA

### ISSUE THREAD

**Issue by 391a** [RapidScada/scada-v6#58]
Hello.
Is a RapidSCADA docker image planned?

**Comment by 2mik** [comment]
Hello,
Community help would be helpful in creating a docker image.
There is a [topic](https://forum.rapidscada.ru/?topic=%d1%81%d0%be%d0%b7%d0%b4%d0%b0%d0%bd%d0%b8%d0%b5-docker-%d0%be%d0%b1%d1%80%d0%b0%d0%b7%d0%b0) on the Russian forum. You could start similar topic on the [international forum](https://forum.rapidscada.org/).

**Comment by geffzhang** [comment]
This is a docker image : https://github.com/geffzhang/RapidScada6

**Comment by 2mik** [comment]
Cool! Is there an instruction how to install it on Linux in English?

**Comment by geffzhang** [comment]
#RapidScada6

RapidScada6 docker containers come with most of the features of systemd. You can use [Dockerfile](./dockerfile) to build a RapidScada6 systemd-enabled container.

In order to run containers with systemd, you need to mount the cgroups volume from the host machine.

[Multiple OSs Docker containers (systemd included)](https://github.com/aminvakil/docker-os-systemd)

Since Rapidskada uses "systemd", you need to use Podman (https://podman.io/) instead of Docker to run the container. Podman's syntax is the same as Docker's, so there shouldn't be any complications. )

Build container & push to dockerhub
```
podman build -f dockerfile -t rapidscada:1.8 .
podman push docker.io/geffzhang/rapidscada_6:1.8

```
To start the container, enter the command:
```
podman run –name rapidscada -p 10000:10000 -p 10002:10002 -p 10008:10008 docker.io/geffzhang/rapidscada_6:1.8
podman exec -it rapidscada bash
```
 
By default, Podman requires entering the full address of the container to download, for example: podman run quay.io/aminvakil/ubuntu22.04-systemd, or in our case, podman run docker.io/geffzhang/rapidscada_6:1.8.
In order for docker to not enter its full address and be able to execute the command: podman login, you need to change the file by creating: $HOME/.config/containers/registries.conf with the content:
unqualified-search-recistries = ["docker.io"]
